[package]
name = "fetch"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "~0.4"
libc = "~0.2"
nvml-wrapper = "~0.9"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
