unstable_features = true
brace_style = "PreferSameLine"
comment_width = 110
condense_wildcard_suffixes = true
# control_brace_style = "ClosingNextLine"
edition = "2021"
enum_discrim_align_threshold = 20
error_on_line_overflow = true
error_on_unformatted = false
# fn_params_layout = "Compressed"
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
match_arm_blocks = false
max_width = 100
newline_style = "Native"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 20
trailing_comma = "Never"
trailing_semicolon = false
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
where_single_line = true
